# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

collector = 0
threeback = 0
twoback = 1
oneback = 2

while (oneback < 4000000)
  collector += oneback if (oneback % 2 == 0)
  threeback = twoback
  twoback = oneback
  oneback = twoback + threeback
end

puts collector


